### ISSUE TITLE
Stop of RAxML-NG with unknown error

### ISSUE THREAD

**Issue by ATVincent** [amkozlov/raxml-ng#39] opened 2018-01-10 18:04 UTC
Hello,
I tried to run RAxML-NG using a partitioned dataset with models defined by ModelTest-NG. However, RAxML-NG stopped prematurely (see the attached file). I tried to compile the tool myself and get almost the same error; only the path was different.

Thank you!
[screenlog.txt](https://github.com/amkozlov/raxml-ng/files/1619924/screenlog.txt)

**Comment by amkozlov** [comment] 2018-01-10 20:03
HI Vincent,

thanks for reporting, this looks like a bug.

1) Could you please re-run the same command with `--log debug` and post the output?
2) Can I get you dataset? (my e-mail: alexey.kozlov(--at--)h-its.org)

Thanks!

**Comment by amkozlov** [comment] 2018-01-24 01:10
This bug must be now fixed in the dev branch:

https://github.com/amkozlov/raxml-ng/tree/dev

**Comment by amkozlov** [comment] 2018-05-22 21:20
Closing since this appears to be fixed in the latest version. 
@ATVincent please feel free to re-open if you can still reproduce the issue .

**Closed by amkozlov** 2018-05-22 21:20 UTC
